name: "Test Rail Parser"
description: "Parsing test rail template test ids and comparing with cucumber tags"
inputs:
  TESTRAIL_USER:
    description: "user email for testrail auth"
    required: true
  TESTRAIL_API_KEY:
    description: "TestRail API key"
    required: true
  testrail-url:
    description: "testrail host url"
    required: true
  testrail-plan-id:
    description: "testrail target plan id"
    required: true
  test-directory:
    description: "directory to search for .feature files"
    required: true
    default: "./tests/features"
outputs:
  missing-ids:
    description: "Test Ids missing from testrail template"
  false-execution-ids:
    description: "Automated Test Ids with false execution values"
runs:
  using: "node16"
  main: "dist/index.js"
