name: Matrix test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  weekly-test:
    name: Testing matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, development-tungsten]
    steps:
      - name: Print out branches
        if: always()
        run: |
          echo "${{ matrix.branch }}"
